<?xml version="1.0"?>
<robot name="SimpleArm"  xmlns:xacro="http://www.ros.org/wiki/xacro">
  <link name="world"/>
  <xacro:property name="altura_base" value="0.1"/>
  <xacro:property name="largo" value="0.5"/>
  <xacro:property name="ancho" value="0.1"/>
  <xacro:property name="masa" value="5"/>
  <xacro:property name="delta" value="0.1"/>

  <xacro:macro name="cuboid_inertia_def" params="x y z mass">
    <inertial>
      <origin xyz="0 0 ${z/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia 
        iyy="${mass*(z*z+x*x)/12.0}"
        ixx="${mass*(y*y+z*z)/12.0}"
        izz="${mass*(x*x+y*y)/12.0}"
        ixy="0.0" iyz="0.0" ixz="0.0"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="default_inertial" params="mass length radius">
    <inertial>
      <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
          <inertia ixx="${mass*(3.0*radius*radius+length*length)/12.0}"
             iyy="${mass*(3.0*radius*radius+length*length)/12.0}"
             izz="${mass*radius*radius/2.0}"
             ixy="0.0" iyz="0.0" ixz="0.0"/>
    </inertial>
  </xacro:macro>

  <xacro:include filename="$(find SimpleArm)/urdf/SimpleArm.gazebo" />

   <!-- Import Rviz colors -->
<xacro:include filename="$(find SimpleArm)/urdf/materials.xacro" />

  <link name="link0">
    <visual>
      <origin xyz="0 0 ${altura_base/2}" rpy="0 0 0"/>
      <geometry>
        <box size="1 1 ${altura_base}"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 ${altura_base/2}" rpy="0 0 0"/>
      <geometry>
        <box size="1 1 ${altura_base}"/>
      </geometry>
    </collision>

   <xacro:cuboid_inertia_def mass="1000" z="${altura_base}" x="1" y="1"/>
  </link>

  <link name="link1">
    <visual>
      <geometry>
        <cylinder radius="${ancho}" length="${largo}"/>
      </geometry>
      <origin xyz="0 0 ${largo/2}" rpy="0 0 0" />
      <material name="orange"/>
    </visual>

    <collision>
      <geometry>
         <cylinder radius="${ancho}" length="${largo}"/>
      </geometry>
      <origin xyz="0 0 ${largo/2}" rpy="0 0 0" />
    </collision>

    <xacro:default_inertial mass="${masa}" length="${largo}" radius="${ancho}"/>
  </link>

  <link name="link2">
    <visual>
      <geometry>
        <cylinder radius="${ancho}" length="${largo}"/>
      </geometry>
      <origin xyz="0 0 ${largo/2}" rpy="0 0 0" />
      <material name="white"/>
    </visual>

    <collision>
      <geometry>
         <cylinder radius="${ancho}" length="${largo}"/>
      </geometry>
      <origin xyz="0 0 ${largo/2}" rpy="0 0 0" />
    </collision>
    <xacro:default_inertial mass="${masa}" length="${largo}" radius="${ancho}"/>
  </link>

  <link name="link3">
    <visual>
      <geometry>
        <cylinder radius="${ancho}" length="${largo}"/>
      </geometry>
      <origin xyz="0 0 ${largo/2}" rpy="0 0 0" />
      <material name="orange"/>
    </visual>

    <collision>
      <geometry>
         <cylinder radius="${ancho}" length="${largo}"/>
      </geometry>
      <origin xyz="0 0 ${largo/2}" rpy="0 0 0" />
    </collision>
    <xacro:default_inertial mass="${masa}" length="${largo}" radius="${ancho}"/>
  </link>

  <link name="link4">
    <visual>
      <geometry>
        <cylinder radius="${ancho}" length="${largo}"/>
      </geometry>
      <origin xyz="0 0 ${largo/2}" rpy="0 0 0" />
      <material name="white"/>
    </visual>

    <collision>
      <geometry>
         <cylinder radius="${ancho}" length="${largo}"/>
      </geometry>
      <origin xyz="0 0 ${largo/2}" rpy="0 0 0" />
    </collision>
    <xacro:default_inertial mass="${masa}" length="${largo}" radius="${ancho}"/>
  </link>
 
  <link name="link5">
    <visual>
      <geometry>
        <sphere radius="${ancho}"/>
      </geometry>
      <origin xyz="0 0 ${ancho}" rpy="0 0 0" />
      <material name="brown"/>
    </visual>

    <collision>
      <geometry>
        <sphere radius="${ancho}"/>
      </geometry>
      <origin xyz="0 0 ${ancho}" rpy="0 0 0" />
    </collision>
    <xacro:default_inertial mass="${masa/20}" length="${ancho}" radius="${ancho}"/>
  </link>

  <joint name="joint0" type="fixed">
    <parent link="world"/>
    <child link="link0"/>
  </joint>

  <joint name="joint1" type="continuous">
    <parent link="link0"/>
    <child link="link1"/>
    <origin xyz="0 0 ${altura_base}" rpy="0 0 0" />
    <axis xyz="0 0 1"/>
    <dynamics damping="0.6"/>
  </joint>

  <joint name="joint2" type="continuous">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 ${largo+delta}" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
    <dynamics damping="0.6"/>
  </joint>

  <joint name="joint3" type="continuous">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 0 ${largo+delta}" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
    <dynamics damping="0.6"/>
  </joint>

  <joint name="joint4" type="continuous">
    <parent link="link3"/>
    <child link="link4"/>
    <origin xyz="0 0 ${largo+delta}" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
    <dynamics damping="0.6"/>
  </joint>

  <joint name="joint5" type="fixed">
    <parent link="link4"/>
    <child link="link5"/>
    <origin xyz="0 0 ${largo}" rpy="0 0 0" />
    </joint>

  <!-- Transmission -->
  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="yaw">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="pitch1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
</transmission>
<transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="pitch2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran4">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint4">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="pitch3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
</transmission>

</robot>


