
SimpleArm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 70.0, i: 0.00, d: 100.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 1500.0, i: 100.0, d: 150.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 400.0, i: 100.0, d: 50.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint4
    pid: {p: 160.0, i: 10.0, d: 8.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}